### ISSUE TITLE
Unable to pip install dev mode after our tag releases

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub/iohub#123]
I was unable to install iohub to a fresh conda environment with `pip install -e .`
I think we will have to drop the custom tag (`0.1.0.dev3`) and use some standard versioning scheme. I think it supports `0.1.0.dev0` but not `0.1.0.dev3`. 

```python
Obtaining file:///hpc/mydata/eduardo.hirata/repos/iohub
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Traceback (most recent call last):
        File "/hpc/mydata/eduardo.hirata/.conda/envs/pyplay/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/hpc/mydata/eduardo.hirata/.conda/envs/pyplay/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/hpc/mydata/eduardo.hirata/.conda/envs/pyplay/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 179, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 454, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 935, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 60, in _assign_version
          maybe_version = _get_version(config)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 156, in _get_version
          version_string = format_version(
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 554, in format_version
          main_version = _call_version_scheme(
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 542, in _call_version_scheme
          result = scheme(version)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 296, in guess_next_dev_version
          return version.format_next_version(guess_next_version)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 192, in format_next_version
          guessed = guess_next(self, *k, **kw)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 244, in guess_next_version
          return _bump_dev(version) or _bump_regex(version)
        File "/tmp/pip-build-env-o4_nlaf_/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 271, in _bump_dev
          raise ValueError(
      ValueError: choosing custom numbers for the `.devX` distance is not supported.
       The 0.1.0.dev3 can't be bumped
      Please drop the tag or create a new supported one ending in .dev0
      [end of output]
```

**Comment by ziw-liu** [comment]
Might need to tell `setuptools_scm` to stop inferring dev version numbers.

This issue seems to be only affecting developers.
