### ISSUE TITLE
CLI for summarizing and converting between data formats

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub/iohub#21]
`recOrder` provides CLI for summarizing ND data without loading it, and converting from OME-TIFF to OME-zarr format. These CLI are more broadly useful and therefore should be moved to `iohub`.

The consensus was to use the `click` library to implement CLI.

**Comment by mattersoflight** [comment]
The current `iohub info` CLI or examples that write test datasets have a couple of bugs. 

* When I create the dataset with ngff example scripts, and run `iohub info`, I get a warning that ZarrReader interface is being used. The CLI should first try `open_ome_zarr` API and fall back to appropriate `ZarrReader` API if the format is older. 

```
(mantis) ➜  examples git:(main) iohub info ~/hcs.zarr
iohub: N-dimensional bioimaging I/O

Reading file:	 /Users/shalin.mehta/hcs.zarr
[WARNING: zarrfile:  33 2023-02-24 20:19:23,816] `iohub.zarrfile.ZarrReader` is deprecated and will be removed in the future. For OME-NGFF (OME-Zarr) v0.4 datasets please use `iohub.ngff.open_ome_zarr` instead.
Positions:	 4
Time points:	 5
Channels:	 4
(Z, Y, X):	 (2, 32, 32)
Channel names:	 ['DAPI', 'GFP', 'Brightfield', 'Segmentation']
Z step (um):	 None
```

* The `iohub info` CLI fails on standard `ome.zarr` file. May be fixed when the default reader for zarr is switched to `open_ome_zarr`.

```
mantis) ➜  examples git:(imread) iohub info ~/ome.zarr
iohub: N-dimensional bioimaging I/O

Reading file:	 /Users/shalin.mehta/ome.zarr
[WARNING: zarrfile:  33 2023-02-24 20:21:25,295] `iohub.zarrfile.ZarrReader` is deprecated and will be removed in the future. For OME-NGFF (OME-Zarr) v0.4 datasets please use `iohub.ngff.open_ome_zarr` instead.
Traceback (most recent call last):
  File "/Users/shalin.mehta/miniconda3/envs/mantis/bin/iohub", line 8, in <module>
    sys.exit(cli())
  File "/Users/shalin.mehta/miniconda3/envs/mantis/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shalin.mehta/miniconda3/envs/mantis/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shalin.mehta/miniconda3/envs/mantis/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shalin.mehta/miniconda3/envs/mantis/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shalin.mehta/miniconda3/envs/mantis/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shalin.mehta/Documents/code/iohub/iohub/cli/cli.py", line 22, in info
    reader = imread(file)
  File "/Users/shalin.mehta/Documents/code/iohub/iohub/reader.py", line 175, in imread
    return ZarrReader(path, version=ngff_version)
  File "/Users/shalin.mehta/Documents/code/iohub/iohub/zarrfile.py", line 50, in __init__
    raise ValueError(f"Invalid NGFF version: {version}")
ValueError: Invalid NGFF version: True

```
