### ISSUE TITLE
NGFF version is not found by `imread`

### ISSUE THREAD

**Issue by talonchandler** [czbiohub/iohub#90]
Running:
```
python single_fov_ome_zarr.py
iohub info ~/ome.zarr
```
yields:
```
Traceback (most recent call last):                                                                                    |103 # this array is about 10 GB, each time point is about 100 MB                    |
  File "/opt/anaconda3/envs/iohub-dev/bin/iohub", line 8, in <module>                                                 |104 # it may not be actually larger than RAM but enough for demo                    |
    sys.exit(cli())                                                                                                   |105 # monitor the memory usage of python when the following runs                    |
  File "/opt/anaconda3/envs/iohub-dev/lib/python3.9/site-packages/click/core.py", line 1130, in __call__              |106 # and it should take significantly less than 10 GB                              |
    return self.main(*args, **kwargs)                                                                                 |107 large_tczyx = da.ones((300, 2, 25, 1024, 1024), dtype=np.uint16)                |
  File "/opt/anaconda3/envs/iohub-dev/lib/python3.9/site-packages/click/core.py", line 1055, in main                  |108                                                                                 |
    rv = self.invoke(ctx)                                                                                             |109 if store_path:                                                                  |
  File "/opt/anaconda3/envs/iohub-dev/lib/python3.9/site-packages/click/core.py", line 1657, in invoke                |110     with open_ome_zarr(                                                         |
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                           |111         store_path, layout="fov", mode="w-", channel_names=["DAPI", "GFP"]      |
  File "/opt/anaconda3/envs/iohub-dev/lib/python3.9/site-packages/click/core.py", line 1404, in invoke                |112     ) as dataset:                                                               |
    return ctx.invoke(self.callback, **ctx.params)                                                                    |113         img = dataset.create_zeros(                                             |
  File "/opt/anaconda3/envs/iohub-dev/lib/python3.9/site-packages/click/core.py", line 760, in invoke                 |114             name="0",                                                           |
    return __callback(*args, **kwargs)                                                                                |115             shape=large_tczyx.shape,                                            |
  File "/Users/talon.chandler/iohub/iohub/cli/cli.py", line 22, in info                                               |116             dtype=large_tczyx.dtype,                                            |
    reader = imread(file)                                                                                             |117             chunks=(1, 1, 1, 1024, 1024),  # chunk by XY planes                 |
  File "/Users/talon.chandler/iohub/iohub/reader.py", line 177, in imread                                             |118         )                                                                       |
    return ZarrReader(path, version=ngff_version)                                                                     |119         for t, not_so_large_czyx in tqdm(enumerate(large_tczyx)):               |
  File "/Users/talon.chandler/iohub/iohub/zarrfile.py", line 50, in __init__                                          |120             img[t] = not_so_large_czyx.compute()                                |
    raise ValueError(f"Invalid NGFF version: {version}")                                                              |121         dataset.print_tree()                                                    |
ValueError: Invalid NGFF version: True
```

This might be a shallow bug. It seems that NGFF stores the version at `['omero']['version']` instead of `['plate']['version']`. See https://github.com/czbiohub/iohub/blob/26855833ddae316e1a5a1561e717aa70b07e886e/iohub/reader.py#L42

**Comment by ziw-liu** [comment]
While this *is* a bug in that `imread` should be able to read what iohub writes, I can now recall the reason I wrote it this way:

Currently `imread` dispatches to the legacy `ZarrReader` for all NGFF versions. So since the legacy reader only reads HCS plates and not single-FOVs, it will fail even this is fixed.

Maybe https://github.com/czbiohub/iohub/issues/21#issuecomment-1444986369 is the way to go, if we are okay with `imread` returning an NGFF node object instead of a `ReaderBase` child.
